/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.project.employeemanagement;

import dev.project.employeemanagement.model.Employee;
import dev.project.employeemanagement.repository.EmployeeRepository;
import java.sql.SQLException;
import java.util.List;
import javafx.application.Application;
import javafx.collections.FXCollections;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Separator;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
  private final EmployeeRepository repository = new EmployeeRepository();
  private final TableView<Employee> table = new TableView<>();
  private final TextField searchField = new TextField();

  private final TextField nameField = new TextField();
  private final TextField ssnField = new TextField();
  private final TextField salaryField = new TextField();
  private final TextField jobTitleField = new TextField();
  private final TextField divisionField = new TextField();
  private Employee selectedEmployee;

  @Override
  public void start(Stage primaryStage) {
    primaryStage.setTitle("Employee Management System - Company Z");

    // header
    Label title = new Label("COMPANY Z - EMPLOYEE PORTAL");
    title.getStyleClass().add("header-title");
    HBox header = new HBox(title);
    header.setPadding(new Insets(15, 10, 0, 15));

    // search
    HBox searchBar = new HBox(10);
    searchBar.setAlignment(Pos.CENTER_LEFT);
    searchBar.setPadding(new Insets(10, 10, 10, 15));
    searchField.setPromptText("Search by Name, SSN, or ID...");
    searchField.setPrefWidth(300);
    Button searchButton = new Button("Search");
    searchButton.setOnAction(e -> handleSearch());
    searchBar.getChildren().addAll(new Label("Search:"), searchField, searchButton);

    // table view
    setupTable();

    // edit/update panel
    VBox updatePanel = createUpdatePanel();

    // salary increase panel
    HBox salaryPanel = createSalaryPanel();

    // layout
    BorderPane root = new BorderPane();
    root.setTop(new VBox(5, header, searchBar));
    root.setCenter(table);
    root.setRight(updatePanel);
    root.setBottom(salaryPanel);

    Scene scene = new Scene(root, 1100, 700);

    try {
      scene.getStylesheets().add(getClass().getResource("/style.css").toExternalForm());
    } catch (Exception e) {
      System.out.println("CSS could not be loaded: " + e.getMessage());
    }

    primaryStage.setScene(scene);
    primaryStage.show();

    handleSearch();
  }

  private void setupTable() {
    TableColumn<Employee, Integer> idCol = new TableColumn<>("ID");
    idCol.setCellValueFactory(new PropertyValueFactory<>("empid"));
    idCol.setPrefWidth(50);

    TableColumn<Employee, String> nameCol = new TableColumn<>("Name");
    nameCol.setCellValueFactory(new PropertyValueFactory<>("name"));

    TableColumn<Employee, String> ssnCol = new TableColumn<>("SSN");
    ssnCol.setCellValueFactory(new PropertyValueFactory<>("ssn"));

    TableColumn<Employee, Double> salaryCol = new TableColumn<>("Salary");
    salaryCol.setCellValueFactory(new PropertyValueFactory<>("salary"));

    table.getColumns().addAll(idCol, nameCol, ssnCol, salaryCol);

    table
        .getSelectionModel()
        .selectedItemProperty()
        .addListener(
            (obs, oldVal, newVal) -> {
              if (newVal != null) {
                selectedEmployee = newVal;
                nameField.setText(newVal.getName());
                ssnField.setText(newVal.getSsn());
                salaryField.setText(String.valueOf(newVal.getSalary()));
                jobTitleField.setText(newVal.getJobTitle());
                divisionField.setText(newVal.getDivision());
              }
            });

    table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
  }

  private VBox createUpdatePanel() {
    VBox panel = new VBox(12);
    panel.setPadding(new Insets(20));
    panel.setPrefWidth(280);
    panel.getStyleClass().add("side-panel");

    Button updateBtn = new Button("Save Changes");
    updateBtn.setMaxWidth(Double.MAX_VALUE);
    updateBtn.setOnAction(e -> handleUpdate());

    panel
        .getChildren()
        .addAll(
            new Label("UPDATE SELECTED EMPLOYEE"),
            new Separator(),
            new Label("Name:"),
            nameField,
            new Label("SSN:"),
            ssnField,
            new Label("Salary:"),
            salaryField,
            new Label("Job Title"),
            jobTitleField,
            new Label("Division"),
            divisionField,
            new Separator(),
            updateBtn);
    return panel;
  }

  private HBox createSalaryPanel() {
    HBox panel = new HBox(15);
    panel.setAlignment(Pos.CENTER_LEFT);
    panel.setPadding(new Insets(20));
    panel.getStyleClass().add("bottom-panel");

    TextField pctField = new TextField();
    pctField.setPromptText("% Increase");
    pctField.setPrefWidth(100);
    TextField minField = new TextField();
    minField.setPromptText("Min Salary");
    TextField maxField = new TextField();
    maxField.setPromptText("Max Salary");
    Button applyBtn = new Button("Apply Batch Salary Increase");

    applyBtn.setOnAction(e -> handleSalaryIncrease(pctField, minField, maxField));

    panel
        .getChildren()
        .addAll(
            new Label("BATCH UPDATE:"),
            pctField,
            new Label("RANGE:"),
            minField,
            new Label("TO"),
            maxField,
            applyBtn);
    return panel;
  }

  private void handleSearch() {
    try {
      List<Employee> results = repository.searchEmployees(searchField.getText());
      table.setItems(FXCollections.observableArrayList(results));
    } catch (SQLException e) {
      showAlert("Database Error", "Failed to search employees: " + e.getMessage());
    }
  }

  private void handleUpdate() {
    if (selectedEmployee == null) {
      return;
    }

    try {
      selectedEmployee.setName(nameField.getText());
      selectedEmployee.setSsn(ssnField.getText());
      selectedEmployee.setSalary(Double.parseDouble(salaryField.getText()));
      selectedEmployee.setJobTitle(jobTitleField.getText());
      selectedEmployee.setDivision(divisionField.getText());

      repository.updateEmployee(selectedEmployee);
      handleSearch();
      showAlert("Success", "Employee updated successfully.");
    } catch (Exception e) {
      showAlert("Error", "Check your inputs and try again: " + e.getMessage());
    }
  }

  private void handleSalaryIncrease(TextField p, TextField min, TextField max) {
    try {
      double pct = Double.parseDouble(p.getText());
      double minSal = Double.parseDouble(min.getText());
      double maxSal = Double.parseDouble(max.getText());

      repository.updateSalariesInRange(pct, minSal, maxSal);
      handleSearch();
      showAlert("Success", "Batch update complete!");
    } catch (Exception e) {
      showAlert("Input Error", "Please enter valid numeric values for the salary range.");
    }
  }

  private void showAlert(String title, String content) {
    Alert alert = new Alert(Alert.AlertType.INFORMATION);
    alert.setTitle(title);
    alert.setHeaderText(null);
    alert.setContentText(content);
    alert.showAndWait();
  }

  public static void main(String[] args) {
    launch(args);
  }
}
